[package]
name = "dr-script"
version = "0.5.4"
edition = "2024"
authors = ["dratyti"]
description = "Простой язык программирования с минималистичным синтаксисом"
license = "MIT"
repository = "https://github.com/dratyti/dr-script"
keywords = ["programming-language", "interpreter", "rust"]
categories = ["development-tools"]

[lib]
name = "dr_script"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "dr-script"
path = "src/main.rs"

[dependencies]
logos = "0.15.1"
clap = {version = "4.5.51", features = ["derive"]}
colored = "3.0.0"
lazy_static = "1.5.0"
